### ISSUE TITLE
should ignore dotfiles when scanning for packages

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [faassen/bowerstatic#46]
my bower.json is in the project root
bowerstatic tries to find the latest file in virtualenvs and tox as well

ignoring dotfiles in gernal would be nice

**Comment by faassen** [comment]
There is something I don't understand about this bug report. If your bower.json is in project root, you're presumably treating your project root as a local bower package for some reason, which is so odd it doesn't sound right.

Otherwise, bower.json (or .bower.json) should only exist under a specific bower_components directory. Did you mean to say you install bower components directly into the project root instead of in a bower_components subdirectory?

**Comment by faassen** [comment]
I'm including a fix for what I just said in 0.8, please let me know if that fixes this issue too.

**Comment by RonnyPfannschmidt** [comment]
in my setup i have a $ROOT/bower.json and a $ROOT/bower_components/ directory

**Comment by RonnyPfannschmidt** [comment]
https://bitbucket.org/RonnyPfannschmidt/mybox/src
the bower script does a local install of bower, then runs bower install in the root

**Comment by faassen** [comment]
Ah, I see now why you'd have a bower.json in the root, to pull in the required dependencies.

Still don't understand why it should scan the root directory instead of just bower_components (which shouldn't be containing dot files). Anyway, I do ignore dotfiles now in the scanning in 0.8; let me know if that fixes your problem?

**Comment by RonnyPfannschmidt** [comment]
the local component is in the root directory

**Comment by RonnyPfannschmidt** [comment]
specifically https://bitbucket.org/RonnyPfannschmidt/mybox/src/90bf9df5e40fe75e6302e4d2c64621b4088aa140/mybox/app.py?at=default#cl-14

**Comment by RonnyPfannschmidt** [comment]
closing to get rid of open issues related to me
